# Kernel configuration file selection.
# See the arch-symbols script for a list of symbols defined.
# -syms excludes a flavor from the kernel-syms package (vanilla is excluded
# automatically).

#
# IMPORTANT: the subdirectory names map to cpuarch
#            kernel-binary and kernel-source rely on this
#

# Grsecurity
+x86_64		x86_64/grsec-server
+x86_64		x86_64/grsec-desktop
+x86_64		x86_64/grsec-guest-kvm
+i386		i386/grsec-server
+i386		i386/grsec-desktop
+armv6hl	armv6hl/grsec-server
